# Regression

In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [28]:
california_data = fetch_california_housing(as_frame=True)
df = california_data.frame

### 1. Loading and Preprocessing

● Load the California Housing dataset using the fetch_california_housing function
from sklearn.

In [29]:
california_data = fetch_california_housing(as_frame=True)

● Convert the dataset into a pandas DataFrame for easier handling. Handle
missing values (if any) and perform necessary feature scaling (e.g.,
standardization).

In [30]:
df = california_data.frame
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [31]:
df.isnull().sum()

MedInc         0
HouseAge       0
AveRooms       0
AveBedrms      0
Population     0
AveOccup       0
Latitude       0
Longitude      0
MedHouseVal    0
dtype: int64

In [32]:
x =df.drop("MedHouseVal", axis=1)
y = df["MedHouseVal"]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(x)

In [33]:

X_scaled = pd.DataFrame(
    X_scaled,
    columns=x.columns
)
X_scaled.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,2.344766,0.982143,0.628559,-0.153758,-0.974429,-0.049597,1.052548,-1.327835
1,2.332238,-0.607019,0.327041,-0.263336,0.861439,-0.092512,1.043185,-1.322844
2,1.782699,1.856182,1.155620,-0.049016,-0.820777,-0.025843,1.038503,-1.332827
3,0.932968,1.856182,0.156966,-0.049833,-0.766028,-0.050329,1.038503,-1.337818
4,-0.012881,1.856182,0.344711,-0.032906,-0.759847,-0.085616,1.038503,-1.337818

● Explain the preprocessing steps you performed and justify why they are
necessary for this dataset.

The California Housing dataset was loaded using the fetch_california_housing() function from the Scikit-learn library. The parameter as_frame=True was used to make the dataset easier to work with in Pandas format.

### 2. Regression Algorithm Implementation

● Implement the following regression algorithms:
○ Linear Regression
○ Decision Tree Regressor
○ Random Forest Regressor
○ Gradient Boosting Regressor
○ Support Vector Regressor (SVR)

In [35]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

### 1  Linear Regression

In [38]:
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)
y_pred_linear = linear_model.predict(X_test)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
20046,-1.152489,-0.289187,-0.499896,-0.156976,-0.029562,0.077681,0.200449,0.279366
3024,-0.705015,0.108104,-0.157477,0.204301,0.123206,-0.037634,-0.230283,0.054757
15663,-0.205588,1.856182,-0.586814,0.188231,-0.101972,-0.164679,1.015093,-1.432653
20484,0.982710,-0.924851,0.296929,-0.161370,0.246834,0.035990,-0.632923,0.424114
9814,-0.076678,0.425936,0.025864,-0.144836,-0.320086,-0.056520,0.462633,-1.178096

### 2️ Decision Tree Regressor

In [ ]:
from sklearn.tree import DecisionTreeRegressor
tree_model = DecisionTreeRegressor(random_state=42)
tree_model.fit(X_train, y_train)
y_pred_tree = tree_model.predict(X_test)

### 3️ Random Forest Regressor

In [40]:
from sklearn.ensemble import RandomForestRegressor
forest_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)
forest_model.fit(X_train, y_train)
y_pred_forest = forest_model.predict(X_test)

### 4️ Gradient Boosting Regressor

In [41]:
from sklearn.ensemble import GradientBoostingRegressor
gradient_model = GradientBoostingRegressor(
    random_state=42
)
gradient_model.fit(X_train, y_train)
y_pred_gradient = gradient_model.predict(X_test)

### 5️ Support Vector Regressor (SVR)

In [42]:
from sklearn.svm import SVR
svr_model = SVR()
svr_model.fit(X_train, y_train)
y_pred_svr = svr_model.predict(X_test)

# 3. Model Evaluation and Comparison

### ● Evaluate the performance of each algorithm using the following metrics:
○ Mean Squared Error (MSE)
○ Mean Absolute Error (MAE)
○ R-squared Score (R2)

In [43]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
mse_linear = mean_squared_error(y_test, y_pred_linear)
mae_linear = mean_absolute_error(y_test, y_pred_linear)
r2_linear = r2_score(y_test, y_pred_linear)
print("Linear Regression Results")
print("MSE:", mse_linear)
print("MAE:", mae_linear)
print("R² Score:", r2_linear)

Linear Regression Results
MSE: 0.5558915986952441
MAE: 0.5332001304956565
R² Score: 0.575787706032451

In [44]:
mse_tree = mean_squared_error(y_test, y_pred_tree)
mae_tree = mean_absolute_error(y_test, y_pred_tree)
r2_tree = r2_score(y_test, y_pred_tree)
print("Decision Tree Results")
print("MSE:", mse_tree)
print("MAE:", mae_tree)
print("R² Score:", r2_tree)

Decision Tree Results
MSE: 0.4942716777366763
MAE: 0.4537843265503876
R² Score: 0.6228111330554302

In [45]:
mse_forest = mean_squared_error(y_test, y_pred_forest)
mae_forest = mean_absolute_error(y_test, y_pred_forest)
r2_forest = r2_score(y_test, y_pred_forest)
print("Random Forest Results")
print("MSE:", mse_forest)
print("MAE:", mae_forest)
print("R² Score:", r2_forest)

Random Forest Results
MSE: 0.25549776668540763
MAE: 0.32761306601259704
R² Score: 0.805024407701793

In [46]:
mse_gradient = mean_squared_error(y_test, y_pred_gradient)
mae_gradient = mean_absolute_error(y_test, y_pred_gradient)
r2_gradient = r2_score(y_test, y_pred_gradient)
print("Gradient Boosting Results")
print("MSE:", mse_gradient)
print("MAE:", mae_gradient)
print("R² Score:", r2_gradient)

Gradient Boosting Results
MSE: 0.29399901242474274
MAE: 0.37165044848436773
R² Score: 0.7756433164710084

In [47]:
mse_svr = mean_squared_error(y_test, y_pred_svr)
mae_svr = mean_absolute_error(y_test, y_pred_svr)
r2_svr = r2_score(y_test, y_pred_svr)
print("SVR Results")
print("MSE:", mse_svr)
print("MAE:", mae_svr)
print("R² Score:", r2_svr)

SVR Results
MSE: 0.3551984619989416
MAE: 0.3977630963437863
R² Score: 0.7289407597956463

In [48]:
results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Decision Tree",
        "Random Forest",
        "Gradient Boosting",
        "SVR"
    ],

    "MSE": [
        mse_linear,
        mse_tree,
        mse_forest,
        mse_gradient,
        mse_svr
    ],

    "MAE": [
        mae_linear,
        mae_tree,
        mae_forest,
        mae_gradient,
        mae_svr
    ],

    "R² Score": [
        r2_linear,
        r2_tree,
        r2_forest,
        r2_gradient,
        r2_svr
    ]
})

print(results)

               Model       MSE       MAE  R² Score
0  Linear Regression  0.555892  0.533200  0.575788
1      Decision Tree  0.494272  0.453784  0.622811
2      Random Forest  0.255498  0.327613  0.805024
3  Gradient Boosting  0.293999  0.371650  0.775643
4                SVR  0.355198  0.397763  0.728941

### The best-performing algorithm

In [49]:
best_model = results.loc[results["R² Score"].idxmax()]

print("Best Performing Model:")
print(best_model)

Best Performing Model:
Model       Random Forest
MSE              0.255498
MAE              0.327613
R² Score         0.805024
Name: 2, dtype: object

### The worst-performing algorithm

In [50]:
worst_model = results.loc[results["R² Score"].idxmin()]

print("Worst Performing Model:")
print(worst_model)

Worst Performing Model:
Model       Linear Regression
MSE                  0.555892
MAE                    0.5332
R² Score             0.575788
Name: 0, dtype: object