In [34]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

In [42]:
df=pd.read_csv("winequalityred.csv",sep=";")
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

1. Load the dataset and handle any missing data by replacing null values with the mean
value of the respective column.

In [44]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [45]:
df.fillna(df.mean(numeric_only=True))

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

2. Extract the following columns as vectors: alcohol,citric acid.

In [53]:
alcohol=df["alcohol"].values
cirtric_acid=df["citric acid"].values
print("alcohol=",alcohol)
print("cirtric acid=",cirtric_acid)

alcohol= [ 9.4  9.8  9.8 ... 11.  10.2 11. ]
cirtric acid= [0.   0.   0.04 ... 0.13 0.12 0.47]

3. Select two features (e.g., alcohol and density) from the dataset and calculate the
covariance matrix using np.cov(X.T), where X is the feature matrix consisting of the
selected columns.

In [55]:
x = df[["alcohol","density"]].values
print(x)

[[ 9.4      0.9978 ]
 [ 9.8      0.9968 ]
 [ 9.8      0.997  ]
 ...
 [11.       0.99574]
 [10.2      0.99547]
 [11.       0.99549]]

In [64]:
cov_mtr=np.cov(x.T)
print("Covariance Matrix:")
print(cov_mtr)

Covariance Matrix:
[[ 1.13564740e+00 -9.97951790e-04]
 [-9.97951790e-04  3.56202945e-06]]

4. Perform eigen decomposition on the covariance matrix you computed in question 3.
Identify and interpret the results:Identify the top 2 eigenvalues of the covariance
matrix,Identify the corresponding eigenvectors.

In [57]:
eigenvalues, eigenvectors = np.linalg.eig(cov_mtr)

print("Eigenvalues:")
print(eigenvalues)

print("Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[1.13564827e+00 2.68507580e-06]
Eigenvectors:
[[ 9.99999614e-01  8.78753184e-04]
 [-8.78753184e-04  9.99999614e-01]]

Identify the top 2 eigenvalues

In [58]:
idx = np.argsort(eigenvalues)[::-1]

eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]

print("Top 2 Eigenvalues:")
print(eigenvalues[:2])

print("Corresponding Eigenvectors:")
print(eigenvectors[:, :2])

Top 2 Eigenvalues:
[1.13564827e+00 2.68507580e-06]
Corresponding Eigenvectors:
[[ 9.99999614e-01  8.78753184e-04]
 [-8.78753184e-04  9.99999614e-01]]

5. Which wine quality is most common in the dataset? How can you interpret the
distribution of wine quality scores?

In [59]:
quality_counts = df["quality"].value_counts()

print(quality_counts)

quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64

In [60]:
most_common = df["quality"].mode()[0]

print("Most common wine quality:", most_common)

Most common wine quality: 5